name: Check compliance with Arduino Repository rules

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Check for compliance
        uses: arduino/arduino-lint-action@v1.0.0
        with:
            library-manager: update
            project-type: library
            compliance: strict
